[CyS](COMPONENTES)(CONEXIONES)(YO*ACREEDORA*):! AUTOMOTOR|INMOBILIARIO
[PLATA](CASA)(OBJETOS)(CAPITAL);! *OTRO*DEUDOR
[ARTE](EXCLUSIVIDAD)(PREGUNTAS)(MISIONES);! NOVIO
[INFORMACIÓN](AVAL);! SÍMBOLO
[TRANSPORTE](AUTONOMÍA)(CULPAS/CASTIGOS)(TRUEQUES);! MOTO-150Cc.
